### ISSUE TITLE
[Fabric 1.20.1] Dedicated server crash upon adding empty maps to atlas

### ISSUE THREAD

**Issue by jakeismyname** [MehVahdJukaar/mapatlases-neoforge#76] opened 2024-01-03 19:49 UTC
Crash log: https://mclo.gs/ktbxgeh
Tested in minimal environment, only happens on dedicated servers.

**Comment by MehVahdJukaar** [comment] 2024-01-03 22:32
duplicate of issue below

**Closed as completed by MehVahdJukaar** 2024-01-03 22:32 UTC
